---
- name: play Install Geerlingguy Docker
  hosts: default
  become: true
  vars:
    docker_edition: "ce"
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose: true
    docker_compose_version: "1.26.0"
    docker_compose_path: /usr/local/bin/docker-compose
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_apt_ignore_key_error: True
    docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    docker_users:
      - ubuntu

  pre_tasks:
    - name: Add universe repository for focal
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal universe
        state: present
      when: ansible_distribution_release == 'focal'
    - name: Install gnupg2
      apt:
        name: gnupg2
        state: present
        update_cache: yes

  roles:
    - geerlingguy.docker

- name: play Install the latest goss
  hosts: default
  become: true
  roles:
    - vantaworks.goss

- name: play Install consul
  hosts: default
  become: true
  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      when: "ansible_os_family|lower == 'debian'"

    - name: Add Debian/Ubuntu Linux repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        update_cache: true
      when: "ansible_os_family|lower == 'debian'"

    - name: Install consul and vault
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - consul
        - vault

- name: play Install envoy
  hosts: default
  become: true
  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key
        state: present
      when: "ansible_os_family|lower == 'debian'"

    - name: Add Debian/Ubuntu Linux repository
      apt_repository:
        repo: "deb [arch=amd64] https://deb.dl.getenvoy.io/public/deb/ubuntu {{ ansible_distribution_release }} main"
        state: present
        update_cache: true
      when: "ansible_os_family|lower == 'debian'"

    - name: Install envoy
      apt:
        name: getenvoy-envoy
        state: present
